name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
softdepend: [PremiumVanish, LuckPerms, PAPIProxyBridge, SayanVanish]
api-version: 1.21

main: ${mainClass}

commands:
    njoinspoof:
        description: Send a fake join or leave message from the proxy.
        permission: networkjoinmessages.spoof
        usage: /<command>
    njoinreload:
        description: Reloads the configuration file.
        permission: networkjoinmessages.reload
        usage: /<command>
    njointoggle:
        description: Toggles incoming join messages.
        permission: networkjoinmessages.toggle
        usage: /<command>
    njoinimport:
        description: Imports usercache.json files.
        permission: networkjoinmessages.import
        usage: /<command>
permissions:
    networkjoinmessages.spoof:
        description: "Allows the use of the /njoinspoof command."
        default: op
    networkjoinmessages.reload:
        description: "Allows the use of the /njoinreload command."
        default: op
    networkjoinmessages.toggle:
        description: "Allows the use of the /njointoggle command."
        default: op
    networkjoinmessages.import:
        description: "Allows the use of the /njoinimport command."
        default: op
    networkjoinmessages.silent:
        description: "The holder will not trigger any messages."
        default: false